 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/inboxes", type: :request do
  
  # Inbox. As you add validations to Inbox, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Inbox.create! valid_attributes
      get inboxes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      inbox = Inbox.create! valid_attributes
      get inbox_url(inbox)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_inbox_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      inbox = Inbox.create! valid_attributes
      get edit_inbox_url(inbox)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Inbox" do
        expect {
          post inboxes_url, params: { inbox: valid_attributes }
        }.to change(Inbox, :count).by(1)
      end

      it "redirects to the created inbox" do
        post inboxes_url, params: { inbox: valid_attributes }
        expect(response).to redirect_to(inbox_url(Inbox.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Inbox" do
        expect {
          post inboxes_url, params: { inbox: invalid_attributes }
        }.to change(Inbox, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post inboxes_url, params: { inbox: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested inbox" do
        inbox = Inbox.create! valid_attributes
        patch inbox_url(inbox), params: { inbox: new_attributes }
        inbox.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the inbox" do
        inbox = Inbox.create! valid_attributes
        patch inbox_url(inbox), params: { inbox: new_attributes }
        inbox.reload
        expect(response).to redirect_to(inbox_url(inbox))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        inbox = Inbox.create! valid_attributes
        patch inbox_url(inbox), params: { inbox: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested inbox" do
      inbox = Inbox.create! valid_attributes
      expect {
        delete inbox_url(inbox)
      }.to change(Inbox, :count).by(-1)
    end

    it "redirects to the inboxes list" do
      inbox = Inbox.create! valid_attributes
      delete inbox_url(inbox)
      expect(response).to redirect_to(inboxes_url)
    end
  end
end
